### ISSUE TITLE
请问大佬 The fastest ip for 这个是怎么判断是最好的IP

### ISSUE THREAD

**Issue by gitv2ray** [lifenjoiner/dnsforwarder#1]
在goodiplist.c 的 91行有
INFO("The fastest ip for `%s' is %s\n",
请问是怎么判断出最好的IP，如果是比较时间，请问这个时间保存在哪里，
如果能显示出这个IP的时间就更好，如:
Apr 05 19:52:12 [INFO] The fastest ip for `list1' is 1.1.1.1 250ms

**Comment by lifenjoiner** [comment]
之前没有收到提醒，才发现你的问题。

依据：
定期 TCP 连接，取的最先返回。

显示这个延迟时间其实没什么意义，不管多少，它都是这个方法得出来的结果，参考而已。况且被放到这里的都是特殊对象，TCP 连接响应速度已经决定不了实际线路质量了。

**Comment by gitv2ray** [comment]
感谢大佬，就是在那个发起请求和返回后加两个时间就能知道延时

**Comment by lifenjoiner** [comment]
已添加。
