### ISSUE TITLE
free(): double free detected in tcache 2

### ISSUE THREAD

**Issue by harbinbeer** [lifenjoiner/dnsforwarder#15]
Configure File : /root/.dnsforwarder/config

Mar 02 21:19:18 [INFO] New session.
Mar 02 21:19:18 [INFO] UDP interface 0.0.0.0:53 opened.
Mar 02 21:19:18 [INFO] TCP interface 0.0.0.0:53 opened.
Mar 02 21:19:18 [INFO] Loading Server Groups completed.
Mar 02 21:19:18 [INFO] Loading GroupFile(s) completed.
Mar 02 21:19:18 [INFO] Setting DisabledType succeeded.
Mar 02 21:19:18 [INFO] Loading DisabledDomain completed.
Mar 02 21:19:18 [INFO] Loading DisabledList completed.
Mar 02 21:19:18 [INFO] Local hosts file : "/root/.dnsforwarder/hosts.txt"
Mar 02 21:19:18 [INFO] Loading the existing hosts file ...
Mar 02 21:19:18 [INFO] Loading hosts completed.
Mar 02 21:19:18 [INFO] Loading Configuration completed.
Mar 02 21:19:18 [INFO] Getting hosts from file:///root/.dnsforwarder/hosts.txt ...
Mar 02 21:19:18 [INFO] Hosts file:///root/.dnsforwarder/hosts.txt saved.
Mar 02 21:19:18 [INFO] Hosts saved at /root/.dnsforwarder/hosts.txt.
Mar 02 21:19:18 [INFO] Loading hosts completed.
Mar 02 21:19:18 [INFO] Loading DisabledDomain completed.
Mar 02 21:19:18 [INFO] Loading DisabledList completed.
Mar 02 21:19:18 [INFO] Loading Server Groups completed.
Mar 02 21:19:18 [INFO] Loading GroupFile(s) completed.
Mar 02 21:19:18 [INFO] Reloading Modules completed.
free(): double free detected in tcache 2
Abort

**Comment by lifenjoiner** [comment]
I can't reproduce it.

More info are needed to diagnose:
1. Your OS version, compiling flags etc.
2. Does it occur occasionally or always?
