### ISSUE TITLE
能否将IPSubstituting的参数从一个IP改成 IP段？

### ISSUE THREAD

**Issue by yy1984** [lifenjoiner/dnsforwarder#2]
适用场景：Cloudflare的CDN

默认返回的IP不一定是最快的。可以用其他程序找到最快的IP，然后用DnsForwarder替换CF的所有IP段

https://www.cloudflare.com/ips-v4
https://github.com/XIU2/CloudflareSpeedTest

**Comment by lifenjoiner** [comment]
想法挺好的，只是最初的设计是 IP 提前转成数字格式后使用的，就限定了是单个IP，改成 IP 段是个大改，我没有很好的方案。
换个思路，建议使用 hosts，给你常访问的域名指定选好的 IP，这样配合`HostsUpdateInterval`和`HostsScript`还能自动更新。

**Comment by lifenjoiner** [comment]
已实现，且添加了更便利的`IPSubstitutingFile`。
