### ISSUE TITLE
何时能增加tcplocal？

### ISSUE THREAD

**Issue by w311ang** [lifenjoiner/dnsforwarder#7]
https://github.com/lifenjoiner/dnsforwarder/blob/a2cf519cc597aa927a7ef1d223f96d308f2fa311/default.config#L53
作为dnsmasq上游dns时，若上游不支持tcp，dnsmasq就会返回`end of file`

**Comment by lifenjoiner** [comment]
了解一下，这两个软件的什么特性，使你做这样的组织方式的

**Comment by w311ang** [comment]
> 了解一下，这两个软件的什么特性，使你做这样的组织方式的

我主要是为了udp转tcp和过滤ipv6，我知道tcp到tcp有点离谱但我在用ss连接到家里时要用tcp dns，要是直连或走代理会失去dnsmasq ipset的特性，自己设的hosts都不能用了，sagernet可以改成udp dns+udp over tcp的连接方式，但我要连机场的节点一般都没有udp或udp over tcp，又要改成tcp dns

**Comment by lifenjoiner** [comment]
这坑不好填

**Comment by w311ang** [comment]
> 这坑不好填

临时可以用[tcp2udp](https://github.com/q191201771/tcp2udp) ，监听tcp端口转发到dnsforwarder，反正也不常用tcp，要是能原生当然更好

**Comment by lifenjoiner** [comment]
已实现。

**Comment by w311ang** [comment]
谢谢
https://github.com/w311angg/Actions-K2P/commits/ssrplus3
