### ISSUE TITLE
Build error on Linux

### ISSUE THREAD

**Issue by HiGarfield** [lifenjoiner/dnsforwarder#8]
Caused by 
https://github.com/lifenjoiner/dnsforwarder/blob/0717aae08feb51ff769eb30a0265f2a09102e46c/socketpuller.c#L90

On Linux, the structure `fd_set` does not have the member `fd_count`.

**Comment by lifenjoiner** [comment]
Thanks for your test. I'll take a look at it later. There are changes WIP.

**Comment by lifenjoiner** [comment]
Fixed.
